Repository naman14/TimberX, pull requests merged in 2019-02, with the labels that each got.

#18 Begin to implement dependency injection, starting with Notifications service.
  app/build.gradle
  app/src/main/java/com/naman14/timberx/TimberMusicService.kt
  app/src/main/java/com/naman14/timberx/TimberXApp.kt
  app/src/main/java/com/naman14/timberx/extensions/ContextExtensions.kt
  app/src/main/java/com/naman14/timberx/notifications/Notifications.kt
  app/src/main/java/com/naman14/timberx/notifications/NotificationsModule.kt
  dependencies.gradle
Labels: tech debt

#33 Use dependency injection with View Models and Repositories
  app/src/main/java/com/naman14/timberx/MainModule.kt
  app/src/main/java/com/naman14/timberx/MediaSessionConnection.kt
  app/src/main/java/com/naman14/timberx/TimberMusicService.kt
  app/src/main/java/com/naman14/timberx/TimberXApp.kt
  app/src/main/java/com/naman14/timberx/db/DbHelper.kt
  app/src/main/java/com/naman14/timberx/extensions/SongExtensions.kt
  app/src/main/java/com/naman14/timberx/repository/AlbumRepository.kt
  app/src/main/java/com/naman14/timberx/repository/ArtistRepository.kt
  app/src/main/java/com/naman14/timberx/repository/FoldersRepository.kt
  app/src/main/java/com/naman14/timberx/repository/GenreRepository.kt
  app/src/main/java/com/naman14/timberx/repository/PlaylistRepository.kt
  app/src/main/java/com/naman14/timberx/repository/RepositoriesModule.kt
  app/src/main/java/com/naman14/timberx/repository/SongsRepository.kt
  app/src/main/java/com/naman14/timberx/ui/activities/MainActivity.kt
  app/src/main/java/com/naman14/timberx/ui/adapters/FolderAdapter.kt
  app/src/main/java/com/naman14/timberx/ui/dialogs/AddToPlaylistDialog.kt
  app/src/main/java/com/naman14/timberx/ui/fragments/BottomControlsFragment.kt
  app/src/main/java/com/naman14/timberx/ui/fragments/FolderFragment.kt
  app/src/main/java/com/naman14/timberx/ui/fragments/NowPlayingFragment.kt
  app/src/main/java/com/naman14/timberx/ui/fragments/QueueFragment.kt
  app/src/main/java/com/naman14/timberx/ui/fragments/SearchFragment.kt
  app/src/main/java/com/naman14/timberx/ui/fragments/artist/ArtistDetailFragment.kt
  app/src/main/java/com/naman14/timberx/ui/fragments/base/BaseNowPlayingFragment.kt
  app/src/main/java/com/naman14/timberx/ui/fragments/base/MediaItemFragment.kt
  app/src/main/java/com/naman14/timberx/ui/viewmodels/MainViewModel.kt
  app/src/main/java/com/naman14/timberx/ui/viewmodels/MediaItemFragmentViewModel.kt
  app/src/main/java/com/naman14/timberx/ui/viewmodels/NowPlayingViewModel.kt
  app/src/main/java/com/naman14/timberx/ui/viewmodels/SearchViewModel.kt
  app/src/main/java/com/naman14/timberx/ui/viewmodels/ViewModelsModule.kt
  app/src/main/java/com/naman14/timberx/util/InjectorUtils.kt
Labels: tech debt

#34 Add pt-br translations
  app/src/main/res/values-pt-rBR/strings-about.xml
  app/src/main/res/values-pt-rBR/strings.xml
Labels: translations

#43 Fetch Higher resolution images from Last.fm
  app/src/main/java/com/naman14/timberx/network/models/LastfmAlbum.kt
  app/src/main/java/com/naman14/timberx/ui/bindings/LastFmImageBindings.kt
  app/src/main/res/layout/fragment_artist_detail.xml
Labels: enhancement

#46 Add adaptive icon generated by Android Studio.
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: possible improvement
